name: ffmpeg_kit_flutter_test
description: Demonstrates how to use the ffmpeg_kit_flutter plugin.
version: 6.0.2
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter:
    path: ../../../ffmpeg-kit/flutter/flutter
  cupertino_icons: ^1.0.5
  path_provider: ^2.1.0
  path: ^1.8.3
  fluttertoast:
    git:
      url: https://github.com/ponnamkarthik/FlutterToast.git
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
