name: ffmpeg_kit_flutter_test
description: Demonstrates how to use the ffmpeg_kit_flutter plugin.
version: 5.1.0
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter:
    path: ../../../ffmpeg-kit/flutter/flutter
  cupertino_icons: ^1.0.5
  path_provider: ^2.0.11
  path: ^1.8.2
  fluttertoast: ^8.0.9
  video_player: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
